### ISSUE TITLE
breaks calculated values

### ISSUE THREAD

**Issue by blutorange** [blutorange/closure-compiler-maven-plugin#39]
<a href="https://github.com/garretwilson"><img src="https://avatars0.githubusercontent.com/u/627125?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [garretwilson](https://github.com/garretwilson)**
_Monday Sep 03, 2018 at 16:14 GMT_
_Originally opened as https://github.com/samaxes/minify-maven-plugin/issues/161_

----

My source file has this:

```css
.foo {
  font-size: calc(0.5em + 1vw);
}
```

The plugin changes this to:

```css
.foo{font-size:calc(0.5em+1vw)}
```

This is invalid and breaks the value.

This is is a blocker issue. The plugin is broken; I cannot use it.
